/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GvJ50E05JIq
 */
import React from 'react';
import Link from "next/link";

export function MainHero() {
    return (
      <section className="w-full">
        <div className="container px-4 md:px-6 flex flex-col items-start gap-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Meet your digital clone</h1>
          <p className="py-2 max-w-[700px] text-gray-500 dark:text-gray-400">
          Create your digital counterpart, and take breathtaking pictures featuring you.
          It's definitely you, just a better version.
          </p>

          <Link
            className="inline-flex w-100 items-center rounded-full shadow-xl hover:shadow-2xl bg-gray-900 dark:bg-gray-900 text-white text-sm font-normal px-2 py-1"
            href="./login"
            style={{
              borderRadius: "50px",
            }}
          >
            <img
              alt="Double helix"
              className="rounded-full mr-2"
              height={34}
              src="/kep.gif"
              style={{
                aspectRatio: "34/34",
                objectFit: "cover",
              }}
              width={34}
            />
            Create Your Clone&nbsp; 
          </Link>
            <p className="text-xs text-gray-500 dark:text-gray-400">
            Already a member?
            <Link className="underline" href="#">
              Sign In
            </Link>
            </p>
          
        </div>
      </section>
    )
  }
  
  