/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/31yiGNT2Zfd
 */


export function ThreeSteps() {
  return (
    <div className="grid w-full items-center justify-center gap-4 px-4 text-center md:px-6">
      <div className="space-y-2">
        <ul className="grid gap-6 sm:gap-8 lg:gap-12">
          <li className="flex flex-col items-center justify-center space-y-2">
            <div className="flex items-center justify-center w-12 h-12 rounded-full border border-gray-200 bg-gray-100 dark:border-gray-800 dark:bg-gray-950">
              1
            </div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-300">Upload your photos</h3>
            <div className="grid items-center gap-2 text-center">
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
              Use your camera or upload at least 6-12 pictures of you (or the person you want to clone). Make sure that only you are in the picture and that your face is clearly visible.
              </p>
            </div>
            <img
              alt="Image"
              className="aspect-video overflow-hidden rounded-xl object-contain object-center"
              src="/example.png"
            />
          </li>
          <li className="flex flex-col items-center justify-center space-y-2">
            <div className="flex items-center justify-center w-12 h-12 rounded-full border border-gray-200 bg-gray-100 dark:border-gray-800 dark:bg-gray-950">
              2
            </div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-300">Do the magic</h3>
            <div className="grid items-center gap-2 text-center">
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
              Our AI-based service able "learn" your unique features and reproduce them down to the smallest detail.
              </p>
            </div>
            <img
              alt="Image"
              className="aspect-video overflow-hidden rounded-xl object-cover object-center"
              height="280"
              src="/example.png"
              width="500"
            />
          </li>
          <li className="flex flex-col items-center justify-center space-y-2">
            <div className="flex items-center justify-center w-12 h-12 rounded-full border border-gray-200 bg-gray-100 dark:border-gray-800 dark:bg-gray-950">
              3
            </div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-300">Get your amazing photos</h3>
            <div className="grid items-center gap-2 text-center">
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
              With your own model, any picture can be taken of you, as if you had a professional photographer. The only limit is your imagination
              </p>
            </div>
            <img
              alt="Image"
              className="aspect-video overflow-hidden rounded-xl object-cover object-center"
              height="280"
              src="/placeholder.svg"
              width="500"
            />
          </li>
        </ul>
      </div>
    </div>
  )
}
