/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KShQXlHvtYq
 */


export function TrainProcess() {
  return (
    <div className="w-full py-12">
      <div className="container flex flex-col gap-12 px-4 md:px-6">
        <div className="flex flex-col gap-2">
          <h2 className=" text-gray-500 dark:text-gray-400 text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">How it works</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-[minmax(auto,400px)] gap-12">
          <div className="flex items-start gap-4">
            <div className="flex flex-col items-center">
              <div className="w-8 h-8 rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950/90" />
            </div>
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 flex items-center justify-center rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
                  1
                </div>
                <div className="grid gap-0.5">
                  <h3 className="font-semibold">Upload your photos</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                  Use your camera or upload at least 6-12 pictures of you (or the person you want to clone). Make sure that only you are in the picture and that your face is clearly visible.
                  </p>
                  <img
                    alt="Image"
                    className="aspect-video overflow-hidden rounded-xl object-contain object-center"
                    src="/example.png"
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex flex-col items-center">
              <div className="w-2 h-8 rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950" />
              <div className="w-2 h-8 rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950/90" />
            </div>
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 flex items-center justify-center rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
                  2
                </div>
                <div className="grid gap-0.5">
                  <h3 className="font-semibold">Do the magic</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                  Our AI-based service able "learn" your unique features and reproduce them down to the smallest detail.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex flex-col items-center">
              <div className="w-2 h-8 rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950" />
              <div className="w-2 h-8 rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950/90" />
            </div>
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 flex items-center justify-center rounded-full border border-gray-200 border-gray-200 bg-gray-200 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
                  3
                </div>
                <div className="grid gap-0.5">
                  <h3 className="font-semibold">Get your amazing photos</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                  With your own model, any picture can be taken of you, as if you had a professional photographer. The only limit is your imagination
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
